<?php
// vi:ft=php:fdm=indent

/**
 * @file
 * A payment module for Ubercart that provides Rabobank Omnikassa payment.
 */

/**
 * The help function for this module.
 */
function uc_omnikassa_help($path, $arg) {
  switch ($path) {
    case "admin/help#uc_omnikassa":
      return '<p>' . t('Provides Rabobank Omnikassa as a payment method for Ubercart') . '</p>';
      break;
  }
}

/**
 * Generate a data string from an array.
 */
function uc_omnikassa_makedata($array) {
  $data = '';

  foreach ($array as $key => $value) {
    $data .= "|$key=$value";
  }

  return substr($data, 1);
}

/** 
 * Generate a seal from a given data string.
 */
function uc_omnikassa_makeseal($data, $key) {
  return hash('sha256', utf8_encode($data . $key));
}

